### ISSUE TITLE
Noticable Lag in the recorded footage and the actual action 

### ISSUE THREAD

**Issue by amansinghaljpr** [arkhipenko/esp32-mjpeg-multiclient-espcam-drivers#13]
I am using the ESP 32 multi-client code with RTOS and it is extremely slow . Like not exactly slow but its from the actual time of activity to the moment it shows up on the camera its basically 7 -10 seconds. So if i connect this camera with an NVR . How am i supposed to match the timing. Also is there any way to still use the RTOS all frames thingy and decrease the lag or at least make that lag consistent enough . 

Even if i know that the recorded footage is always going to lag by 10 seconds i can account for that . But if that time is a variable then the recorded footage is usable but you just cant match the actions in that footage with respect to time because you never know them in first place that how much lag was there.

**Comment by arkhipenko** [comment]
There is nothing in the code that holds the frames back.

In my experience the lag was caused by 
1. Buffering on the client side (VLC for instance has a default of 1000 ms or so, but you can adjust that)
2. Faulty ESP32-CAM modules (I suspect slow PSRAM chip? I did not investigate). 

ESP-EYE for now is clearly the winner. ESP32-CAM - really depends where you get them from. 
I did not test on any other chips. 

Hope this helps.

**Comment by amansinghaljpr** [comment]
Ok so i am using the AI thinker board . I am not sure about how fast or slow the PSRAM chip is . I followed your exact steps but i didn't exactly understand that why did you actually made people download the esp-cam updated git and put your code into the same folder . What help would it do ? And doesnt the same things already come along when you actually update the Arduino core of esp32 ?

**Comment by arkhipenko** [comment]
Latest Arduino core does not have the latest drivers for the camera. Hence the download.
